### DISCUSSION TITLE
Getting started (as a beginner)

### DISCUSSION THREAD

**Discussion by davidsampimon** [floatingpurr/sync_with_poetry#11] [Q&A] [answered]
I am probably missing something really obvious (I am a beginning programmer), but I can not get sync_with_poetry to work:

1) I updated my .pre-commit-config.yaml file to include sync_with_poetry
2) When I run pre-commit, it skips sync_with_poetry everytime. Also when my .pre-commit-config.yaml is staged

On purpose I left the black rev out-of-sync with my poetry.lock file:

excerpt from .pre-commit-config.yaml
```
repos:
    - repo: https://github.com/floatingpurr/sync_with_poetry
      rev: "0.2.1"
      hooks:
        - id: sync_with_poetry
          language: system
    - repo: https://github.com/psf/black
      rev: 21.11b1
      args: [--line-length=79]
      hooks: 
        -   id: black
```

excerpt from poetry.lock file
```
[[package]]
name = "black"
version = "22.3.0"
description = "The uncompromising code formatter."
category = "dev"
optional = false
python-versions = ">=3.6.2"
```
