### ISSUE TITLE
Alternative solution

### ISSUE THREAD

**Issue by lorenzwalthert** [floatingpurr/sync_with_poetry#10]
Instead of a sync hook, can't you just use the poetry environment for hooks that have a CLI (via `language: system`)? Like with mypy, we do
```yaml
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: poetry run mypy .
        types_or: [ python, pyi ]
        require_serial: true
        pass_filenames: false
```
This also saves space by not creating two environments. What are your thoughts on that approach?
