### ISSUE TITLE
Request: Sync rev of sync_with_poetry and poetry

### ISSUE THREAD

**Issue by Berk-Tosun** [floatingpurr/sync_with_poetry#20]
First of all, great hook!

The idea behind the hook is to have a single source of truth for all our packages, right? The rev of all my pre-commit hooks are managed in the pyproject.toml except for `sync_with_poetry` and `poetry` itself.  I have to adjust my .pre-commit-config.yaml manually, for these two.

**Perhaps, sync of these two special cases can be covered by sync_with_poetry as well?**

---
I have tried using a custom db.json which includes:
```json
    "poetry": {
        "repo": "https://github.com/python-poetry/poetry",
        "rev": "${rev}"
    },
```
It did not work.

---
Relevant part of .pre-commit-config.yaml:
```yaml
- repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0
    hooks:
      - id: sync_with_poetry
        args: [--db, .sync-with-poetry-db.json]
- repo: https://github.com/python-poetry/poetry
    rev: 1.2.0  # sync_with_poetry fails
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
```

**Comment by floatingpurr** [comment]
> First of all, great hook!
>
>The idea behind the hook is to have a single source of truth for all our packages, right? 

Thank you! Yes, you are right. That's exactly the reason why this hook exists.

Regarding your question, I can't replicate what you are describing. Here's my test:

starting `.pre-commit-config.yaml`

```yaml
minimum_pre_commit_version: 2.15.0
repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0
    hooks:
      - id: sync_with_poetry
        args: [--db, .sync-with-poetry-db.json]
  - repo: https://github.com/python-poetry/poetry
    rev: b6d4b0adafb45204aadace143f73a789c1c0e33e # sync_with_poetry works!
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
```

snippet of `pyproject.toml`

```toml
[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
poetry = "^1.2.0"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```


Resulting `.pre-commit-config.yaml` after `sync_with_poetry`

```yaml
minimum_pre_commit_version: 2.15.0
repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0
    hooks:
      - id: sync_with_poetry
        args: [--db, .sync-with-poetry-db.json]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.0 # sync_with_poetry worked!
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
```

Did you put Poetry in your dev dependencies?
