### ISSUE TITLE
sync_with_poetry is skipped when running pre-commit on individual files?

### ISSUE THREAD

**Issue by emocibob** [floatingpurr/sync_with_poetry#40]
Hi, thanks for the great hook :)

I'm testing it on a project with the following structure:

```
.
├── .git
├── foo
│   ├── .pre-commit-config.yaml
│   ├── bar
│   │   └──baz.py
│   ├── poetry.lock
│   ├── poetry.toml
│   ├── pyproject.toml
...
```

When running `pre-commit` on all files in `foo/`, it works as expected.

```
❯ poetry run pre-commit run --all-files
Sync with Poetry.........................................................Passed
isort....................................................................Failed
- hook id: isort
- exit code: 1

ERROR: .../baz.py Imports are incorrectly sorted and/or formatted.

black....................................................................Passed
```

But when my IDE runs `pre-commit` automatically on commits or when I run it on specific files, it says that the hook `Sync with Poetry` was skipped. Here's an example:

```
❯ poetry run pre-commit run --files bar/baz.py
Sync with Poetry.....................................(no files to check)Skipped
isort....................................................................Failed
- hook id: isort
- exit code: 1

ERROR: .../baz.py Imports are incorrectly sorted and/or formatted.

black....................................................................Passed
```

Does this mean `sync_with_poetry` didn't sync the packages?

FYI I'm using `pre-commit` 3.8.0. Here's my `.pre-commit-config.yaml`:

```
repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.2.0
    hooks:
      - id: sync_with_poetry
        args: [--config, foo/.pre-commit-config.yaml]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black, --check-only]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--check, --diff]
```
